runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

set bg=dark
let g:hybrid_custom_term_colors = 1
colo hybrid

syntax on
filetype plugin indent on
set nocp nu si noet ts=4 sw=4 nu tm=150 nosmd gfn=Source\ Code\ Pro\ 10 go=agi cot=menuone
set pt=<F2> t_ZH=[3m t_ZR=[23m
au FileType qf setl nonu cc=

let g:airline_left_sep = ''
let g:airline_right_sep = ''
"let g:airline_powerline_fonts = 1
let g:airline_theme = 'hybridline'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#hunks#non_zero_only = 1

let g:tmuxline_preset = 'full'
let g:tmuxline_powerline_separators = 0

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_error_symbol = 'X'
let g:syntastic_warning_symbol = '!'

let g:SuperTabDefaultCompletionType = '<c-n>'

let g:ycm_confirm_extra_conf = 0
let mapleader=','
au BufNewFile,BufRead ~/source/libinput/*.[ch] setl ts=8 sw=8 cc=80
au FileType qf setl cc=
au FileType location setl cc=

hi Comment cterm=italic, gui=italic
hi LineNr ctermbg=0 ctermfg=7
hi Error ctermbg=0
hi Todo ctermbg=0
